### ISSUE TITLE
图片全部失效

### ISSUE THREAD

**Issue by deamonet** [ityouknow/spring-boot-leaning#14]
所有图片全部失效，就连网站上的图标也显示不出来。似乎是gitbook.cn网站的问题，不过就这样也拿出来卖课？我看评论里两年前都有人提到图片无效了，结果至今都不给解决。

虽然是卖课平台的问题，但至少您得把这个宣传连接改改啊

**Comment by ityouknow** [comment]
网站我没有权限去改
